cxx_binary(
  name = 'AVLTree',
  srcs = [
    'src/TestAVLTree.cpp',
  ],
  deps = [
    '//:forest',
    '//ext:catch',
  ],
)

cxx_binary(
  name = 'BinarySearchTree',
  srcs = [
    'src/TestBinarySearchTree.cpp',
  ],
  deps = [
    '//:forest',
    '//ext:catch',
  ],
)

cxx_binary(
  name = 'RedBlackTree',
  srcs = [
    'src/TestRedBlackTree.cpp',
  ],
  deps = [
    '//:forest',
    '//ext:catch',
  ],
)

cxx_binary(
  name = 'SplayTree',
  srcs = [
    'src/TestSplayTree.cpp',
  ],
  deps = [
    '//:forest',
    '//ext:catch',
  ],
)