cxx_binary(
  name = 'AVLTree',
  srcs = [
    'src/TestAVLTree.cpp',
  ],
  deps = [
    '//:forest',
    '//vendor:catch',
  ],
)

cxx_binary(
  name = 'BinarySearchTree',
  srcs = [
    'src/TestBinarySearchTree.cpp',
  ],
  deps = [
    '//:forest',
    '//vendor:catch',
  ],
)

cxx_binary(
  name = 'KDTree',
  srcs = [
    'src/TestKDTree.cpp',
  ],
  deps = [
    '//:forest',
    '//vendor:catch',
  ],
)

cxx_binary(
  name = 'QuadTree',
  srcs = [
    'src/TestQuadTree.cpp',
  ],
  deps = [
    '//:forest',
    '//vendor:catch',
  ],
)