cxx_binary(
  name = 'avltree', 
  srcs = [
    'src/avltree.cpp', 
  ], 
  deps = [
    '//:forest', 
  ], 
)

cxx_binary(
  name = 'rbtree', 
  srcs = [
    'src/rbtree.cpp', 
  ], 
  deps = [
    '//:forest', 
  ], 
)

cxx_binary(
  name = 'splaytree', 
  srcs = [
    'src/splaytree.cpp', 
  ], 
  deps = [
    '//:forest', 
  ], 
)
